feat: 마이페이지 조회 및 정보 수정, 프로필 이미지 수정 구현
depromeet/Swimie-server pull request #216
Opened 2024-08-14 15:18 UTC by ywonchae1

## 🌱 관련 이슈

- close #213

## 📌 작업 내용 및 특이사항
- **마이페이지 회원 데이터 조회를 구현하였습니다.**
- profileImageUrl, nickname, introduction, 팔로워 수, 팔로잉 수, 자신의 마이페이지인지 여부를 조회할 수 있습니다.
- 다른 사람의 마이페이지에서도 동일한 값을 조회할 수 있으며, `isMyProfile` 값이 `false` 입니다.
---
- **마이페이지 정보 수정을 구현하였습니다.**
- 닉네임, 한 줄 소개를 수정할 수 있습니다. (성별 수정은 논의 중에 있습니다. 목표 수정은 별도로 분리되어 있습니다.)
---
- **마이페이지 프로필 이미지 수정을 구현하였습니다.**
- 프로필 이미지가 없는 경우 새롭게 업로드 하며, 회원 정보의 `profileImageUrl` 을 업데이트 합니다.
- 프로필 이미지가 있는 경우 기존의 이미지를 S3에서 삭제하고, 새로운 이미지를 업로드 하며, 회원 정보의 `profileImageUrl` 을 업데이트 합니다.
- 요청된 새로운 프로필 이미지가 없는 경우 기존의 이미지를 S3에서 삭제하고, 회원 정보의 `profileImageUrl` 을 `null`로 업데이트 합니다.
- 이미지가 있는 경우 `profileImageUrl`은 변환된 uuid를 저장하고 있습니다.
- <mark>회원 정보 조회 시 프로필 이미지는 cloud front 도메인을 붙여 응답하도록 하였습니다.</mark>

## 📝 참고사항
- 나의 마이페이지 회원 정보 조회 성공
<img width="850" alt="Screenshot 2024-08-15 at 00 11 41" src="https://github.com/user-attachments/assets/d6a7b62f-dfb2-4830-8f9b-b96a8411c942">

- 다른 사람 마이페이지 회원 정보 조회 성공
![Screenshot 2024-08-14 at 22 12 09](https://github.com/user-attachments/assets/32706da3-a766-4f89-8013-ecd1283d737b)

- 회원 정보가 없는 경우 실패
<img width="845" alt="Screenshot 2024-08-15 at 00 11 49" src="https://github.com/user-attachments/assets/7791b240-5037-408f-b046-b6090c3d701c">

---

- 마이페이지 정보 수정 성공 - 한 줄 소개 null 가능
<img width="844" alt="Screenshot 2024-08-14 at 22 39 59" src="https://github.com/user-attachments/assets/5c136ccc-be6b-4cc2-80f4-31ae6a1edea6">

- 마이페이지 정보 수정 성공 - 한 줄 소개 공백 가능
<img width="842" alt="Screenshot 2024-08-14 at 22 39 47" src="https://github.com/user-attachments/assets/68fe5806-5a90-4ee1-ad33-c0f3cdd19fa4">

- 마이페이지 정보 수정 성공 - 이름 수정 가능
<img width="847" alt="Screenshot 2024-08-14 at 22 39 26" src="https://github.com/user-attachments/assets/8e316bf3-5550-4207-ac6e-18dda08db545">

- 마이페이지 정보 수정 실패 - 이름 blank 불가
<img width="842" alt="Screenshot 2024-08-14 at 22 39 35" src="https://github.com/user-attachments/assets/42d65bfa-51bf-4b97-bb6f-7d3b39200a89">

---

- 마이페이지 프로필 이미지 수정 성공
<img width="841" alt="Screenshot 2024-08-14 at 23 40 38" src="https://github.com/user-attachments/assets/46fbee22-b7c0-4008-96b3-0f072d2ee324">

- 마이페이지 프로필 이미지 삭제 성공
<img width="842" alt="Screenshot 2024-08-14 at 23 48 35" src="https://github.com/user-attachments/assets/12760d4b-2449-4dff-a6d0-fa8f34622edc">

2024-08-15 03:54 UTC, its-sky requested changes
리뷰 확인 부탁드려요 수고하셨습니다~

2024-08-15 03:54 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
> +                followUseCase.countFollowingByMemberId(memberId),
이 경우에 memberId로 Follower랑 Following count 쿼리를 분리해서 조회하고 있는 것 같습니다! 이를 한번에 조회할 수 있을거 같은데 어떻게 생각하시나요?

2024-08-15 03:54 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/member/dto/request/MemberUpdateRequest.java
> +        @NotBlank(message = "멤버의 이름은 비어 있을 수 없습니다") String nickname, String introduction) {
비단 여기 뿐만 아니라 클라이언트에서 파라미터나 Response Body에서 필수적인 필드와 필수적이지 않은 필드를 명시해달라고 해서 해당 PR에서 Request와 Response에 모두 처리해주시면 좋을거 같습니다!

2024-08-15 03:54 UTC, its-sky commented on module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUpdateUseCase.java
> +
공백이 제거되면 좋을거 같습니다!

2024-08-15 03:54 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
> +    }
Presigned Url 방식이
`클라이언트가 Presigned Url 발급 -> 클라이언트가 해당 Url에 이미지 저장 -> 저장이 성공하면 클라이언트가 서버에 성공 응답`
이런 식이어야 하는데 여기선 왜 프로필 이미지에서 Presigned Url 발급 성공만 있나요?

2024-08-15 03:54 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
> +    }
그리고 PresignedUrl 발급이랑 프로필 이미지 삭제가 같이 있는건 괜찮은데 PUT 메소드로 하는건 어떠신가요? 원래 하나의 API에 생성/삭제 동작이 같이 있을때는 일반적으로 PUT으로 하는걸로 알고 있습니다!

2024-08-15 03:54 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/member/dto/response/MemberProfileResponse.java
> +            Member member, String profileImageDomain, Integer followerCount, Integer followingCount, Boolean isMyProfile) {
Domain은 도메인 클래스로 혼동하게 하는 네이밍인것 같습니다. Origin으로 바꾸는게 어떨지 제안드려봅니다.

2024-08-15 04:58 UTC, penrose15 commented on module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUpdateUseCase.java
> +
이 말 하려 했는데 이미 하셨네요 ㅋㅋㅋ

2024-08-15 05:02 UTC, penrose15 reviewed
수고하셨습니다

2024-08-17 04:50 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
> +                followUseCase.countFollowingByMemberId(memberId),
성주언니가 만들어 둔 메서드를 활용한 상황이었습니다!
한 번에 조회하는 메서드를 새로 만들어서 진행 해볼게요~!

2024-08-17 04:51 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/member/dto/request/MemberUpdateRequest.java
> +        @NotBlank(message = "멤버의 이름은 비어 있을 수 없습니다") String nickname, String introduction) {
아 맞네요 !! 감사합니다~~

2024-08-17 04:51 UTC, ywonchae1 commented on module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUpdateUseCase.java
> +
어머 !!! 감사합니다~~

2024-08-17 04:53 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
> +    }
PUT 메서드 좋습니다!
"저장이 성공하면 클라이언트가 서버에 성공 응답" 이 무슨 뜻인가요? 클라이언트가 서버에게 성공 응답을 보낼 수 있나요??
제가 생각한 건, Memory의 이미지와 다르게 프로필 이미지는 Member 테이블에 저장되기 때문에 서버는 저장된 이미지의 UUID만 저장해 두면 된다고 생각했습니다!

2024-08-17 04:55 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/member/dto/response/MemberProfileResponse.java
> +            Member member, String profileImageDomain, Integer followerCount, Integer followingCount, Boolean isMyProfile) {
요건 성주님이 네이밍하신 것을 그대로 사용한 건데, 바꿔도 괜찮을까요?? @penrose15

2024-08-17 05:02 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
> +    }
UUID 저장까지는 좋습니다! 그런데 저장에 성공했는지 실패했는지에 대한 것을 처리하려면 클라이언트에서 해당 PresignedUrl에 저장을 한 이후 저장이 성공했다는 표시로 성공이라는 표시의 api를 한번 더 호출해야 합니다!

현재는 저장만 하고 클라이언트의 저장이 실패하게 된다면 해당 멤버의 프로필 이미지는 에러가 날테니까요!

2024-08-17 05:03 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
> +    }
이제 클라이언트 측에서 presignedURL 을 활용하여 이미지를 업로드 한 후, 이를 올렸다고 클라이언트에서 다시 우리 쪽으로 응답을 보내는 api를 만들어달라는 뜻 같습니다.

2024-08-17 05:03 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/member/dto/response/MemberProfileResponse.java
> +            Member member, String profileImageDomain, Integer followerCount, Integer followingCount, Boolean isMyProfile) {
넵 바꿔주시면 감사하겠습니다.

2024-08-17 05:03 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
> +    }
오 알겠습니다!
Memory에서도 마찬가지로 진행되고 있나요?? @penrose15

2024-08-17 05:07 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
> +    }
네 진행되고 있습니다 memory에서는 이미지 저장 api 에서 이미지 이름을 받은 후 presigned url을 응답 받으면 클라이언트에서 이를 활용해 presignedurl로 이미지를 업로드 한 후, imageId와 함께 memory 저장을 합니다. 즉, 이미지 저장 확인과 메모리 저장을 같이하고 있어요

2024-08-17 05:09 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
> +    }
감사합니다!! 참고해서 진행할게요 :)

2024-08-18 10:50 UTC, penrose15 commented on module-domain/src/main/java/com/depromeet/image/port/in/ImageUploadUseCase.java
> +    ImagePresignedUrlNameVo getProfileImagePresignedUrl(String originImageName);
ImagePreslgendUrlNameVo 라고 하면 위의 ImagePresignedUrlVo와 이름이 비슷해서 혼동을 줄 수 있을 것 같은데 profilePresignedUrlNameVo로 사용 용도를 명확하게 하는게 어떨까 싶습니다.

2024-08-18 11:07 UTC, penrose15 approved these changes
수고하셨습니다 깔끔하네요

2024-08-18 11:25 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/image/dto/response/ProfileImageUploadResponse.java
> +    public static ProfileImageUploadResponse of(ImagePresignedUrlNameVo imagePresignedUrlNameVo) {
혹시 여기로 nullable 달아줄 수 있나요?

2024-08-19 00:03 UTC, ywonchae1 commented on module-domain/src/main/java/com/depromeet/image/port/in/ImageUploadUseCase.java
> +    ImagePresignedUrlNameVo getProfileImagePresignedUrl(String originImageName);
음.. 이게 좀 복잡한데요!
`ImagePresignedUrlVo`에서 반환하는 `imageName`은 이미지의 원래 이름이고,
`ImagePresignedUrlNameVo`에서 반환하는 `imageName`은 이미지의 UUID 이름이에요.
꼭 profile만을 위한 vo가 아니기도 하구요.
통일하면 좋을 것 같은데 지금 스펙을 바꾸기가 어렵기도 해서요!

2024-08-19 00:04 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/image/dto/response/ProfileImageUploadResponse.java
> +    public static ProfileImageUploadResponse of(ImagePresignedUrlNameVo imagePresignedUrlNameVo) {
넵 감사합니다!!

2024-08-19 00:42 UTC, its-sky approved these changes

2024-08-19 00:48 UTC, merged