Feature/219 following log page
depromeet/Swimie-server pull request #223
Opened 2024-08-17 12:39 UTC by penrose15

## 🌱 관련 이슈

- close #219 

## 📌 작업 내용 및 특이사항
- 팔로잉 소식 조회 API를 개발하였습니다. 
- 팔로잉 소식 페이지에 있는 팔로잉 목록 요약 조회 API를 개발하였습니다. 
- 타임라인에 리엑션 개수를 추가하였습니다. 

## 📝 참고사항
- 팔로잉 소식 조회 API
request
![팔로잉 소식 조회 request](https://github.com/user-attachments/assets/ea432ffc-9697-45eb-877f-26760c30ac51)

response
![팔로잉 소식 조회 response full](https://github.com/user-attachments/assets/e798abb4-e75c-407c-9c55-ce3beed6b735)

만약 팔로워가 수영기록을 등록하고 처음 팔로잉 소식을 조회할 때
![팔로잉 소식 response 최신 소식 true로 조회](https://github.com/user-attachments/assets/39ec3121-936c-4434-8e08-cd407901158d)

이후 다시 새로고침 한 이후 결과
![팔로잉 소식 response 새로 고침 이후 false 로 변경](https://github.com/user-attachments/assets/2a98e213-719a-42b9-9091-b240a89382fc)

가장 마지막 페이지
![팔로잉 소식 response 가장 마지막 페이지 조회](https://github.com/user-attachments/assets/81bcc035-f603-493f-85f2-0cdcd569f4d3)

팔로잉 목록 요약 API
![팔로잉 요약 response](https://github.com/user-attachments/assets/281f4a7d-cfbe-42fc-9b71-80346858ce51)

타임라인에 리액션 개수 추가
![타임라인 reactionCount 추가](https://github.com/user-attachments/assets/b3908c6e-ecbb-4667-866c-48b98cc10f0e)

2024-08-17 12:48 UTC, ywonchae1 commented on module-domain/src/main/java/com/depromeet/followingLog/domain/FollowingMemoryLog.java
> +public class FollowingMemoryLog {
이름 모두 News로 바꾸는 거 아니었나요?

2024-08-17 12:48 UTC, ywonchae1 commented on module-independent/src/main/java/com/depromeet/type/followingLog/FollowingLogErrorType.java
> +        return "";
```suggestion
        return this.code;
```
이렇게 수정 필요할 것 같아요!

2024-08-17 12:48 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
> +                        description = "리액션 개수",
"응원 개수"가 어떨까요??

2024-08-17 12:50 UTC, penrose15 commented on module-domain/src/main/java/com/depromeet/followingLog/domain/FollowingMemoryLog.java
> +public class FollowingMemoryLog {
아 api url 만 바꾸는게 아니었나요?

2024-08-17 12:50 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
> +                        description = "리액션 개수",
ㅇㅎ 그게 낫겠네요

2024-08-17 12:53 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
> +                        description = "리액션 개수",
수정 완료했습니다

2024-08-17 13:11 UTC, ywonchae1 commented on module-domain/src/main/java/com/depromeet/followingLog/domain/FollowingMemoryLog.java
> +public class FollowingMemoryLog {
Swagger에도 "팔로잉 소식(Following Log)" 라고 나와 있기도 해서
전체적으로 코드까지 통일하면 좋을 것 같아요!

2024-08-17 13:51 UTC, its-sky commented on module-domain/src/main/java/com/depromeet/followingLog/domain/FollowingMemoryLog.java
> +public class FollowingMemoryLog {
음 요건 제 생각에는 내부적으로 Log로 하고 api 엔드포인트만 news로 하는게 더 나을거 같은데 다른 분들은 어떠세요?

2024-08-17 13:52 UTC, its-sky commented on module-domain/src/main/java/com/depromeet/followingLog/domain/FollowingMemoryLog.java
> +public class FollowingMemoryLog {
이런 데이터를 내부에 쌓는 것은 로그이지만 이를 외부로 노출시켜서 클라이언트에서는 뉴스로 하는거라고 생각하거든요

2024-08-17 14:01 UTC, penrose15 commented on module-domain/src/main/java/com/depromeet/followingLog/domain/FollowingMemoryLog.java
> +public class FollowingMemoryLog {
현재 followingMemoryLog 엔티티에는 memoryId, memberId 이 두가지만 저장되어 있습니다. 이 엔티티에 저장하는 데이터의 목적이 로그에 더 가깝다고 생각하기 때문에 저도 following log로 하는게 조금 더 나을 것 같습니다. 

아 추가적으로 domain, entity 이름을 followingMemoryLog로 한 이유는 추후에 뱃지나 팔로우 추가 소식이 생긴다면 following~log로 지어야 하는게 맞을 것 같아 네이밍을 그렇게 했습니다.

2024-08-18 04:16 UTC, its-sky requested changes
수고하셨습니다!

2024-08-18 04:16 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/followingLog/facade/FollowingLogCreateFacade.java
> +    }
이벤트를 수신하는 역할을 수행하는데 굳이 `파사드`를 적용시킬 이유가 있을까요? 제 생각에는 `Service`에서 수행해도 충분할거 같다고 생각하는데 의견 있으신가요? 아님 Facade가 아니라 `CreateFollowingMemoryEventListener`라는 클래스를 만들어서 명시적으로 어느 클래스에서 이벤트를 수신하는지를 확고히 해줬으면 더 좋겠습니다!

2024-08-18 04:16 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/followingLog/facade/FollowingLogFacade.java
> +    private final MemberUpdateUseCase memberUpdateUseCase;
길이순 정렬 부탁드려요 ㅎ

2024-08-18 04:16 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/followingLog/facade/FollowingLogFacade.java
> +        Member member = memberUseCase.findById(memberId);
제 생각에는 FollowingLog안에 Memory -> Member를 한번에 FetchJoin 하면 멤버를 한번 더 쿼리로 조회할 일은 없을 거 같습니다!

2024-08-18 04:19 UTC, penrose15 commented on module-domain/src/main/java/com/depromeet/member/domain/Member.java
> +    private LocalDateTime lastViewedFollowingLogAt;
넵 맞습니다. 이전에 회의할 때 팔로잉 소식 최신 조회 유무를 판단하기 위한 필드 하나 추가하기로 헀던 필드입니다. 의도를 명확히 하기 위해서 변수명이 본의아니게 길어지긴 했네요

2024-08-18 04:20 UTC, penrose15 commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/followingLog/entity/FollowingMemoryLogEntity.java
> +    @Column(name = "following_memory_news_id")
앗 이부분은 제가 놓쳤네요 수정하겠습니다

2024-08-18 04:22 UTC, penrose15 commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/followingLog/repository/FollowingMemoryLogRepository.java
> +                .build();
듣고 보니 맞는 소리네요 바꾸는게 더 좋을 것 같습니다.

2024-08-18 04:23 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/followingLog/facade/FollowingLogFacade.java
> +    private final MemberUpdateUseCase memberUpdateUseCase;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-08-18 04:23 UTC, penrose15 commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/followingLog/entity/FollowingMemoryLogEntity.java
> +                .memory(this.memory.toModel())
확인해보겠습니다

2024-08-18 07:58 UTC, ywonchae1 commented on module-domain/src/main/java/com/depromeet/followingLog/domain/FollowingMemoryLog.java
> +public class FollowingMemoryLog {
넵 !! 그럼 Swagger에 보이는 "팔로잉 소식(Following Log)"은 수정이 필요할 거 같습니다

2024-08-18 11:59 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/followingLog/facade/FollowingLogFacade.java
> +        Member member = memberUseCase.findById(memberId);
앗 혹시 followingLog에서 member를 한번에 fetchJoin 한 이후 following log에서 member를 꺼내 쓰면 된다는 의견일까요? followingLog에서 조회하는 member는 로그인 한 사용자의 팔로잉을 조회하고 member 조회 할 때는 로그인 한 사용자를 조회하기 때문에 따로 조회해야 했습니다.

2024-08-18 14:47 UTC, penrose15 commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/followingLog/entity/FollowingMemoryLogEntity.java
> +                .memory(this.memory.toModel())
확인해본 결과 N+1 문제가 나타나서 

```
public FollowingMemoryLog toModel() {
        return FollowingMemoryLog.builder()
                .id(this.id)
                .member(this.member.toModel())
                .memory(this.memory.toModelForFollowingLog())
                .createdAt(getCreatedAt())
                .build();
    }
```
로 변경 및 fetchJoin을 걸어 N+1 문제를 개선하였습니다.

해결이 아니라 개선이라 한 이유는 fetchJoin 을 활용하여 쿼리문을 5개 -> 2개로 줄이는데는 성공하였으나 memory와 oneToMany인 stroke 와 image에 둘다 fetchJoin을 걸 수가 없었기 때문입니다. (2개 이상 거는 경우 MultipleBagFetchException 가 발생합니다.)

2024-08-19 00:54 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/followingLog/dto/response/FollowingLogMemoryResponse.java
> +                        .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
```suggestion
        LocalDateTime createdAt = followingMemoryLog.getCreatedAt();
```
제가 알기로 yyyy-MM-dd HH:mm:ss 패턴의 문자열이 LocalDateTime으로 변환이 잘 되는 걸로 알아서,
이렇게 하면 어떨까 제안 드립니다.
`@Schema(example = "2024-08-16 00:00:00")`만 지정해주면 Swagger에서 보기 편하게 보일 수 있습니다!

2024-08-19 02:53 UTC, ywonchae1 reviewed
반영 감사합니다!

2024-08-19 02:53 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/followingLog/dto/response/FollowingLogMemoryResponse.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
이거 안 해도 될 텐데 적어 주신 이유가 무엇인지 궁금합니다!

2024-08-19 02:57 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/followingLog/dto/response/FollowingLogMemoryResponse.java
> +                        .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
시도 결과 그냥 LocalDateTime으로 반환 시 `yyyy-MM-ddTHH:mm:ss:SSS` 형태로 변환이 되는 것을 확인하였습니다. 현재는 `@JsonFormat` 를 활용하여 `yyyy-MM-dd HH:mm:ss` 로 변환시켰습니다.

- `@JsonFormat 적용 전`
![createdAt LocalDateTime](https://github.com/user-attachments/assets/72b3e019-82c5-4c27-8012-585e3c9672ec)

- `@JsonFormat 적용 후`
![createdAt jsonformat 적용 후](https://github.com/user-attachments/assets/93230483-12e6-41e9-ada0-870378a84c2f)

2024-08-19 02:58 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/followingLog/dto/response/FollowingLogMemoryResponse.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
위의 코멘트에 작성하였으니 확인 부탁합니다

2024-08-19 02:58 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/followingLog/dto/response/FollowingLogMemoryResponse.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
감사합니다

2024-08-19 02:59 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/followingLog/dto/response/FollowingLogMemoryResponse.java
> +                        .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
이거 프론트엔드와도 상의가 된 내용인가요??

2024-08-19 03:07 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/followingLog/dto/response/FollowingLogMemoryResponse.java
> +                        .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
상의 후 알려드리겠습니다.

2024-08-19 07:05 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/followingLog/dto/response/FollowingLogMemoryResponse.java
> +                        .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
상의 결과 그렇게 보내줘도 된다고 하셨습니다

2024-08-19 09:30 UTC, its-sky approved these changes

2024-08-19 09:34 UTC, merged