feat: 100일이 지난 following memory log 일괄 삭제 배치 추가
depromeet/Swimie-server pull request #251
Opened 2024-08-22 08:39 UTC by penrose15

## 🌱 관련 이슈

- close #230

## 📌 작업 내용 및 특이사항
- 100일이 지난 following_memory_log 데이터를 일괄 삭제하는 배치를 추가하였습니다. 
- jenkins에서 이미지 삭제 배치 컨테이너가 실행된 이후 실행되도록 설계하였습니다. 

- `FollowingLogDeleteJobExecutionListener` : 해당 job를 읽어옵니다.
- `FollowingLogItemReader` : 100일이 지난 데이터들을 chunk 단위(10)로 읽어옵니다.
- `FollowingLogItemWriter` : reader에서 읽어온 데이터를 삭제하는 역할을 합니다. 

실행하는 방법: JOB_NAME=followingLogDeleteJob, requestDate=20240801을 변수로 주고 실행합니다.
 

## 📝 참고사항
- memberService에도 `@Profile(!batch)` 를 추가하였습니다. 이유는 memberService가 redis 의존성을 필요로 하는데 배치 모듈에는 필요가 없기 때문입니다. 

100일 전 팔로잉 소식 데이터
![100일전 팔로잉 소식 데이터](https://github.com/user-attachments/assets/2e0abf6d-a87d-4b1d-9e9d-b1b671212ae5)

JOB_NAME=followingLogDeleteJob 환경변수에 추가
![job name 설정](https://github.com/user-attachments/assets/060724d9-ba69-4798-9f6b-9532456d3102)

배치 실행 성공 화면
![batch delete](https://github.com/user-attachments/assets/6134d601-8b4f-4eed-b05c-22b7f6830f95)

삭제가 된 db 결과
![배치 이후 삭제](https://github.com/user-attachments/assets/168e9cf7-7dd0-48c1-87f7-5831db561a85)

+) 로컬 도커 환경에서 prod-batch.sh 실행 시 정상적으로 작동하는 것을 확인하였습니다.

+) 수정사항
- following_memory_log 삭제 배치 파이프라인을 분리하였습니다. 
  - 팔로잉 소식 삭제 배치가 이미지 삭제 배치와 같은 module-batch에 포함되어 있어 같은 도커 레포지토리로 설정해두었습니다.

2024-08-22 21:33 UTC, ywonchae1 requested changes
수고하셨습니다!

2024-08-22 21:33 UTC, ywonchae1 commented on scripts/shell/prod-batch.sh
> +echo "> 9090 포트로 100일 이전의 팔로우 소식 일괄 삭제 배치 작업 컨테이너 실행"
이미지 일괄 삭제 배치 컨테이너는 이미 띄워져 있는 걸로 아는데,
이렇게 하나의 스크립트에 넣으면 팔로우 소식 배치 작업 컨테이너를 실행하기 위해 일괄 삭제 배치 컨테이너를 내렸다가 다시 띄워야 할 것 같아요
파일 분리하면 어떨까요?

2024-08-23 03:16 UTC, penrose15 commented on scripts/shell/prod-batch.sh
> +echo "> 9090 포트로 100일 이전의 팔로우 소식 일괄 삭제 배치 작업 컨테이너 실행"
jenkins 파일을 분리해서 다른 파이프라인에 돌아가게 하자는 뜻인가요?

2024-08-23 03:21 UTC, penrose15 commented
그나저나 오타가 있었네요? 수정 감사합니다 @ywonchae1

2024-08-23 03:29 UTC, ywonchae1 commented on scripts/shell/prod-batch.sh
> +echo "> 9090 포트로 100일 이전의 팔로우 소식 일괄 삭제 배치 작업 컨테이너 실행"
이거 jenkins에서 돌아가는 파일 아닌 걸로 알아요

2024-08-23 03:29 UTC, ywonchae1 commented
> 그나저나 오타가 있었네요? 수정 감사합니다 @ywonchae1

굿 ~~ 컨벤션 지켜줘요 :)

2024-08-23 03:39 UTC, penrose15 commented on scripts/shell/prod-batch.sh
> +echo "> 9090 포트로 100일 이전의 팔로우 소식 일괄 삭제 배치 작업 컨테이너 실행"
![image](https://github.com/user-attachments/assets/54416631-2055-4cd9-b468-ddda1e50d8f8)

아 현재 제가 알기로는 배치 파이프라인이 /scripts/batch/jenkinsfile-image 파일을 기반으로 배치.sh 파일이 실행되는 것으로 알고 있는데 혹시 다른 방법으로 실행되고 있나요?

2024-08-23 06:00 UTC, ywonchae1 commented on scripts/batch/Jenkinsfile-following
> +                        ./batch-following.sh
이 파일 NCP 서버에 존재 하나요?

2024-08-23 06:08 UTC, penrose15 commented on scripts/batch/Jenkinsfile-following
> +                        ./batch-following.sh
ncp 서버에 추가를 한 상태이나, 현재 도커 허브에 최신 배치 파일이 올라간 상태가 아니라 작업은 실패가 뜰겁니다

2024-08-23 07:44 UTC, ywonchae1 approved these changes

2024-08-23 12:44 UTC, merged